# Ignore this`expectation` block. It is required but not used, and will be removed in future versions.
expectations:

  population_size: 10000

version: '3.0'

actions:

  generate_dataset_table:
    run: ehrql:v1 generate-dataset analysis/define_static_dataset.py 
      --output output/data/dataset_static.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/data/dataset_static.csv.gz  
